<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Big Data II - Armazenamento
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Introdução;</li>
  <li>Orientação a coluna;</li>
  <li>Particionamento.</li>
</ol>

---

# **Exercícios**

## 1\. Particionamento e orientação a coluna.

Replique as atividades da aula 3 em sua conta da AWS.

1.1. Faça o download do arquivo `crime.csv` (fonte [Kaggle](https://www.kaggle.com/yamqwe/chicago-crimee?select=chicago_crime_2014.csv)).

In [ ]:
!wget https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/dataset/crime.csv -q -O crime.csv

1.2. Leia os dados em um DataFrame Pandas e crie a coluna `reference_date`.

In [ ]:
# Solução do item 1.2.

import pandas as pd

filename = './crime'

df = pd.read_csv(f'./{filename}.csv')

In [ ]:
df.head()

,index,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,Latitude,Longitude
0,0,9446824,HX100141,01/01/2014 02:00:00 AM,0000X W ILLINOIS ST,0460,BATTERY,SIMPLE,STREET,False,False,1831,18,42.0,8.0,08B,41.890828,-87.630235
1,1,9446748,HX100020,01/01/2014 12:00:00 AM,006XX N DEARBORN ST,0890,THEFT,FROM BUILDING,BAR OR TAVERN,False,False,1832,18,42.0,8.0,06,41.893542,-87.629702
2,2,9446758,HX100030,01/01/2014 12:30:00 AM,052XX W RACE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1523,15,28.0,25.0,14,41.890046,-87.756333
3,3,9446760,HX100027,01/01/2014 12:30:00 AM,053XX W WELLINGTON AVE,0460,BATTERY,SIMPLE,APARTMENT,True,False,2514,25,31.0,19.0,08B,41.935011,-87.759739
4,4,9446764,HX100054,01/01/2014 12:10:00 AM,014XX W LEXINGTON ST,0460,BATTERY,SIMPLE,STREET,False,False,1231,12,25.0,28.0,08B,41.872509,-87.663069

In [ ]:
df.shape

(274423, 18)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274423 entries, 0 to 274422
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   index                 274423 non-null  int64
 1   ID                    274423 non-null  int64
 2   Case Number           274423 non-null  object
 3   Date                  274423 non-null  object
 4   Block                 274423 non-null  object
 5   IUCR                  274423 non-null  object
 6   Primary Type          274423 non-null  object
 7   Description           274423 non-null  object
 8   Location Description  274247 non-null  object
 9   Arrest                274423 non-null  bool
 10  Domestic              274423 non-null  bool
 11  Beat                  274423 non-null  int64
 12  District              274423 non-null  int64
 13  Ward                  274421 non-null  float64
 14  Community Area        274422 non-null  float64
 15  FBI Code              274423 non-null  object
 16  Latitude              269464 non-null  float64
 17  Longitude             269464 non-null  float64
dtypes: bool(2), float64(4), int64(4), object(8)
memory usage: 34.0+ MB

In [ ]:
df.to_parquet('./crime.parquet', engine='pyarrow')

In [ ]:
df.to_parquet('./crime.parquet.gzip', engine='pyarrow', compression='gzip')

1.3. Persista o dado no DataFrame em um arquivo csv e em arquivos parquet, estes últimos comprimidos e particionados pela coluna `reference_date`.

In [ ]:
# Solução do item 1.3.

from datetime import datetime

df['reference_date'] = df['Date'].apply(lambda date: datetime.strptime(date.split(sep=' ')[0], '%m/%d/%Y').strftime('%Y-%m-%d'))

In [ ]:
df.tail()

,index,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,Latitude,Longitude,reference_date
274418,274418,10362481,HY554205,08/15/2014 09:00:00 PM,048XX N CLARK ST,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,APARTMENT,False,False,2032,20,46.0,3.0,11,NaN,NaN,2014-08-15
274419,274419,10362558,HY554336,08/31/2014 03:00:00 AM,028XX W 19TH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOSPITAL BUILDING/GROUNDS,False,False,1022,10,12.0,30.0,02,NaN,NaN,2014-08-31
274420,274420,10363233,HY554972,02/20/2014 12:00:00 PM,046XX W NORTH AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,False,False,2533,25,37.0,25.0,11,NaN,NaN,2014-02-20
274421,274421,10363368,HY555019,09/02/2014 09:00:00 AM,047XX N BEACON ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,1913,19,46.0,3.0,11,NaN,NaN,2014-09-02
274422,274422,10364473,HY556366,12/04/2014 09:00:00 AM,012XX W LUNT AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,2431,24,49.0,1.0,11,NaN,NaN,2014-12-04

In [ ]:
agg_df = pd.DataFrame(df['reference_date'].value_counts()).sort_index().reset_index()
agg_df = agg_df.rename(columns={'reference_date': 'amount'})
agg_df = agg_df.rename(columns={'index': 'reference_date'})

In [ ]:
agg_df.tail()

         amount  count
360  2014-12-27    716
361  2014-12-28    631
362  2014-12-29    677
363  2014-12-30    570
364  2014-12-31    577

In [ ]:
df.to_parquet('./crime', engine='pyarrow', compression='gzip', partition_cols='reference_date')

In [ ]:
df.to_csv('./crime_enriched.csv', sep=',', index=False)

1.4. Crie os recursos no AWS S3 e AWS IAM e persista os dados em seus respectivos *buckets*.

- S3 -> modulo41-exercicio-csv -> crime_enriched.csv
- S3 -> modulo41-exercicio-parquet
- IAM -> modulo41 -> modulo41 -> chave de acesso: / chave de acesso secreta:

In [ ]:
# Solução do item 1.4.

from getpass import getpass

aws_access_key_id = getpass()

··········

In [ ]:
from getpass import getpass

aws_secret_access_key = getpass()

··········

In [ ]:
!pip install boto3

Requirement already satisfied: boto3 in /usr/local/lib/python3.11/dist-packages (1.37.2)
Requirement already satisfied: botocore<1.38.0,>=1.37.2 in /usr/local/lib/python3.11/dist-packages (from boto3) (1.37.2)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /usr/local/lib/python3.11/dist-packages (from boto3) (0.11.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.11/dist-packages (from botocore<1.38.0,>=1.37.2->boto3) (2.8.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.11/dist-packages (from botocore<1.38.0,>=1.37.2->boto3) (2.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.38.0,>=1.37.2->boto3) (1.17.0)

In [ ]:
import boto3

client = boto3.client(
  's3',
  aws_access_key_id=aws_access_key_id,
  aws_secret_access_key=aws_secret_access_key
)

In [ ]:
import os

BUCKET = 'modulo41-exercicio-parquet'

i = 0

for root, dirs, files in os.walk('./crime'):
  elapsed = f'{round(100*i/365, 2)} %'
  print(elapsed)
  for file in files:
    path = os.path.join(root, file)
    bucket_path = '/'.join(path.split(sep='/')[2:])
    client.upload_file(path, BUCKET, bucket_path)
  i = i + 1

0.0 %
0.27 %
0.55 %
0.82 %
1.1 %
1.37 %
1.64 %
1.92 %
2.19 %
2.47 %
2.74 %
3.01 %
3.29 %
3.56 %
3.84 %
4.11 %
4.38 %
4.66 %
4.93 %
5.21 %
5.48 %
5.75 %
6.03 %
6.3 %
6.58 %
6.85 %
7.12 %
7.4 %
7.67 %
7.95 %
8.22 %
8.49 %
8.77 %
9.04 %
9.32 %
9.59 %
9.86 %
10.14 %
10.41 %
10.68 %
10.96 %
11.23 %
11.51 %
11.78 %
12.05 %
12.33 %
12.6 %
12.88 %
13.15 %
13.42 %
13.7 %
13.97 %
14.25 %
14.52 %
14.79 %
15.07 %
15.34 %
15.62 %
15.89 %
16.16 %
16.44 %
16.71 %
16.99 %
17.26 %
17.53 %
17.81 %
18.08 %
18.36 %
18.63 %
18.9 %
19.18 %
19.45 %
19.73 %
20.0 %
20.27 %
20.55 %
20.82 %
21.1 %
21.37 %
21.64 %
21.92 %
22.19 %
22.47 %
22.74 %
23.01 %
23.29 %
23.56 %
23.84 %
24.11 %
24.38 %
24.66 %
24.93 %
25.21 %
25.48 %
25.75 %
26.03 %
26.3 %
26.58 %
26.85 %
27.12 %
27.4 %
27.67 %
27.95 %
28.22 %
28.49 %
28.77 %
29.04 %
29.32 %
29.59 %
29.86 %
30.14 %
30.41 %
30.68 %
30.96 %
31.23 %
31.51 %
31.78 %
32.05 %
32.33 %
32.6 %
32.88 %
33.15 %
33.42 %
33.7 %
33.97 %
34.25 %
34.52 %
34.79 %
35.07 %
35.34 %
35.62 %
35.89 %
36.16 %
36.44 %
36.71 %
36.99 %
37.26 %
37.53 %
37.81 %
38.08 %
38.36 %
38.63 %
38.9 %
39.18 %
39.45 %
39.73 %
40.0 %
40.27 %
40.55 %
40.82 %
41.1 %
41.37 %
41.64 %
41.92 %
42.19 %
42.47 %
42.74 %
43.01 %
43.29 %
43.56 %
43.84 %
44.11 %
44.38 %
44.66 %
44.93 %
45.21 %
45.48 %
45.75 %
46.03 %
46.3 %
46.58 %
46.85 %
47.12 %
47.4 %
47.67 %
47.95 %
48.22 %
48.49 %
48.77 %
49.04 %
49.32 %
49.59 %
49.86 %
50.14 %
50.41 %
50.68 %
50.96 %
51.23 %
51.51 %
51.78 %
52.05 %
52.33 %
52.6 %
52.88 %
53.15 %
53.42 %
53.7 %
53.97 %
54.25 %
54.52 %
54.79 %
55.07 %
55.34 %
55.62 %
55.89 %
56.16 %
56.44 %
56.71 %
56.99 %
57.26 %
57.53 %
57.81 %
58.08 %
58.36 %
58.63 %
58.9 %
59.18 %
59.45 %
59.73 %
60.0 %
60.27 %
60.55 %
60.82 %
61.1 %
61.37 %
61.64 %
61.92 %
62.19 %
62.47 %
62.74 %
63.01 %
63.29 %
63.56 %
63.84 %
64.11 %
64.38 %
64.66 %
64.93 %
65.21 %
65.48 %
65.75 %
66.03 %
66.3 %
66.58 %
66.85 %
67.12 %
67.4 %
67.67 %
67.95 %
68.22 %
68.49 %
68.77 %
69.04 %
69.32 %
69.59 %
69.86 %
70.14 %
70.41 %
70.68 %
70.96 %
71.23 %
71.51 %
71.78 %
72.05 %
72.33 %
72.6 %
72.88 %
73.15 %
73.42 %
73.7 %
73.97 %
74.25 %
74.52 %
74.79 %
75.07 %
75.34 %
75.62 %
75.89 %
76.16 %
76.44 %
76.71 %
76.99 %
77.26 %
77.53 %
77.81 %
78.08 %
78.36 %
78.63 %
78.9 %
79.18 %
79.45 %
79.73 %
80.0 %
80.27 %
80.55 %
80.82 %
81.1 %
81.37 %
81.64 %
81.92 %
82.19 %
82.47 %
82.74 %
83.01 %
83.29 %
83.56 %
83.84 %
84.11 %
84.38 %
84.66 %
84.93 %
85.21 %
85.48 %
85.75 %
86.03 %
86.3 %
86.58 %
86.85 %
87.12 %
87.4 %
87.67 %
87.95 %
88.22 %
88.49 %
88.77 %
89.04 %
89.32 %
89.59 %
89.86 %
90.14 %
90.41 %
90.68 %
90.96 %
91.23 %
91.51 %
91.78 %
92.05 %
92.33 %
92.6 %
92.88 %
93.15 %
93.42 %
93.7 %
93.97 %
94.25 %
94.52 %
94.79 %
95.07 %
95.34 %
95.62 %
95.89 %
96.16 %
96.44 %
96.71 %
96.99 %
97.26 %
97.53 %
97.81 %
98.08 %
98.36 %
98.63 %
98.9 %
99.18 %
99.45 %
99.73 %
100.0 %

1.5. Crie os recursos no AWS Athena e execute as consultas SQL da aula.

In [ ]:
# Solução do item 1.5.

    CREATE EXTERNAL TABLE `crime_csv`(
      `index` bigint,
      `id` string,
      `case number` string,
      `date` string,
      `block` string,
      `iucr` string,
      `primary type` string,
      `description` string,
      `location description` string,
      `arrest` string,
      `domestic` string,
      `beat` string,
      `district` string,
      `ward` string,
      `community area` string,
      `fbi code` string,
      `latitude` string,
      `longitude` string,
      `reference_date` string)
    ROW FORMAT SERDE
      'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    WITH SERDEPROPERTIES (
      'separatorChar' = ',',
      'quoteChar' = '\"',
      'escapeChar' = '\\'
      )
    STORED AS INPUTFORMAT
      'org.apache.hadoop.mapred.TextInputFormat'
    OUTPUTFORMAT
      'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
    LOCATION
      's3://modulo41-exercicio-csv/'
    TBLPROPERTIES (
      "skip.header.line.count"="1")

    SELECT * FROM "default"."crime_csv" limit 10;

query1

    CREATE EXTERNAL TABLE `crime_parquet`(
      `index` bigint,
      `id` bigint,
      `case number` string,
      `date` string,
      `block` string,
      `iucr` string,
      `primary type` string,
      `description` string,
      `location description` string,
      `arrest` boolean,
      `domestic` boolean,
      `beat` bigint,
      `district` bigint,
      `ward` double,
      `community area` double,
      `fbi code` string,
      `latitude` double,
      `longitude` double)
    PARTITIONED BY (
      `reference_date` string)
    ROW FORMAT SERDE
      'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
    STORED AS INPUTFORMAT
      'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
    OUTPUTFORMAT
      'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
    LOCATION
      's3://modulo41-eexercicio-parquet/'

    MSCK REPAIR TABLE `crime_parquet`;

    SELECT * FROM "default"."crime_csv" limit 10;
query2

    SELECT "location description", COUNT(1) as "amount"
    FROM crime_csv
    GROUP BY 1
    ORDER BY 2 DESC;
query3

    SELECT "location description", COUNT(1) as "amount"
    FROM crime_parquet
    GROUP BY 1
    ORDER BY 2 DESC;
query4

    SELECT *
    FROM crime_csv
    WHERE CAST(reference_date as DATE) BETWEEN DATE '2014-12-01' and DATE '2014-12-31'
query5

    SELECT *
    FROM crime_parquet
    WHERE CAST(reference_date as DATE) BETWEEN DATE '2014-12-01' and DATE '2014-12-31'
query6

    SELECT "location description", COUNT(1) as "amount"
    FROM crime_csv
    WHERE CAST(reference_date as DATE) BETWEEN DATE '2014-12-01' and DATE '2014-12-31'
    GROUP BY 1
    ORDER BY 2 DESC
query7

    SELECT "location description", COUNT(1) as "amount"
    FROM crime_parquet
    WHERE CAST(reference_date as DATE) BETWEEN DATE '2014-12-01' and DATE '2014-12-31'
    GROUP BY 1
    ORDER BY 2 DESC
query8